### ISSUE TITLE
create pmem namespace failed with 01.00.00.2381

### ISSUE THREAD

**Issue by zhangningdlut** [01org/ixpdimm_sw#10]
When I want to create pmem namespace with  01.00.00.2381 , I met a problem.
`ixpdimm-cli create -f -namespace -pool {pool_id}  persistentmemorytype=appdirect  

Error: The communications with the device driver failed
`

After using the gdb, I have found that, the commit 16269bf62a9d1419ac94cb41149293b9590d5157
sets sector size for the label.
The commit wants to open "/sys/devices/*/namespace8.0/sector_size", but there are no "sector_size" in pmem, and then, return failed.

I think "sector_size" is just for btt and blk mode, why to set it for pmem?

**Comment by juston-li** [comment]
With 1.2 labels, it is now allowed to set the lba size for pmem labels, by default it is 4K. For 1.1 labels, Linux was treating 0 as 512 anyways so it is set explicitly in that change.

What version of ndctl do you have installed?

**Comment by juston-li** [comment]
This came up for someone on an older kernel where the sysfs attribute doesn't exists. Fix is being reviewed now.

Thanks for reporting the issue!

**Comment by juston-li** [comment]
Fix should be out in the next release 2423+

**Comment by juston-li** [comment]
This should be fixed by https://github.com/intel/ixpdimm_sw/commit/9e5fa6c7a58baf72d9d2f21e20e8e6c231cc2d38 currently in the testing branch
