### ISSUE TITLE
fail to compile ixpdimm-sw 2329

### ISSUE THREAD

**Issue by insanecoderr** [01org/ixpdimm_sw#12]
I compile it on Cross Compile Env of EulerOS.

err occured:
[EulerOS_compile_env /home/ww39/ixpdimm_sw-01.00.00.2329]$ ls
CMakeLists.txt  LICENSE  README.md  build.mk  cmakesetup.cmake  external  install  makefile  output  scripts  src
[EulerOS_compile_env /home/ww39/ixpdimm_sw-01.00.00.2329]$ make RELEASE=1
fatal: No names found, cannot describe anything.
mkdir -p ./output/build/linux/real/release
mkdir -p ./output/tools/linux/real/release
make -C src/common  all SKIP_UNITTESTS=1 ADD_MANUFACTURING=0
make[1]: Entering directory `/home/ww39/ixpdimm_sw-01.00.00.2329/src/common'
make[1]: *** No rule to make target `all'.  Stop.
make[1]: Leaving directory `/home/ww39/ixpdimm_sw-01.00.00.2329/src/common'
make: *** [all] Error 2
[EulerOS_compile_env /home/ww39/ixpdimm_sw-01.00.00.2329]$

by the way, the guidebook mentioned that libndctl and invm-framework is required to build before ixpdimm-sw, and is there any version requirement for them to cooperate well?

@juston-li

**Comment by insanecoderr** [comment]
I have solved the compling matter by using cmake recommended. However why the ixpdimm-cli shows that the version of it is 99.99.99.9999 instead of 2329?

[EulerOS_compile_env /home/ww39/ixpdimm_sw-01.00.00.2329/output/build/linux/real/release]$ ./ixpdimm-cli version
Component                         Version
Intel DIMM Gen 1 Software Version 99.99.99.9999
Intel DIMM Gen 1 Driver Version   Error: The underlying software is missing or incompatible with this version of the management software.

**Comment by juston-li** [comment]
Hmm it should use the closest git tag. I'll look into that.
You can manually pass the version to cmake too, -DBUILDNUM=01.00.00.2329

For the build requirements, I think we expect libndctl 58.2. invm-frameworks is included in the build as a submodule.
Build dependency checking by CMake will be added soon.

**Comment by insanecoderr** [comment]
Thanks for your reply , it works.

by the way,about the build requirements,is that i should use the libndctl58.2 and invm-frameworks with master branch？or other branches works too？

**Comment by juston-li** [comment]
Yes ndctl 58.2. master of invm-frameworks should be fine. The submodule will grab the correct version too.

**Comment by insanecoderr** [comment]
Okay,thanks
