### ISSUE TITLE
ixpdimm-cli create namespace:communications with the device driver failed

### ISSUE THREAD

**Issue by insanecoderr** [01org/ixpdimm_sw#14]
env info:

OS:fedora25 
kernel:4.12.13
ixpdimm-sw:2399
invm-framework:2399
ndctl:58.2

I tried to create interleaved app direct namespace on AEP（2-1-1population,single CPU),then error occured:

[root@host-aep4 ~]# ixpdimm-cli show -dimm
DimmID Capacity  HealthState ActionRequired LockState FWVersion
0x0001 125.7 GiB Healthy     0              Disabled  01.00.00.4445
0x0101 125.7 GiB Healthy     0              Disabled  01.00.00.4445

[root@host-aep4 ~]# ls /dev/pmem*
ls: cannot access '/dev/pmem*': No such file or directory
[root@host-aep4 ~]# ixpdimm-cli show -pool
PoolID                               PersistentMemoryType Capacity  FreeCapacity
51428255-2a16-6258-b876-f9a2d33cb55b AppDirect            250.0 GiB 250.0 GiB

[root@host-aep4 ~]# ixpdimm-cli create -namespace -pool 51428255-2a16-6258-b876-f9a2d33cb55b persistentmemorytype=appdirect
Error: The communications with the device driver failed.
[root@host-aep4 ~]# uname -a
Linux host-aep4 4.12.13-200.fc25.x86_64 #1 SMP Thu Sep 14 16:12:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@host-aep4 ~]#reboot

After reboot, show -pool or show -namespace command failed for the reason:floating point exception. However,the namespace seems to be successfully created since /dev/pmem2 appears.
below is my operation log and the software log:

[root@host-aep4 ~]# ixpdimm-cli show -dimm
DimmID Capacity  HealthState ActionRequired LockState FWVersion
0x0001 125.7 GiB Healthy     0              Disabled  01.00.00.4445
0x0101 125.7 GiB Healthy     0              Disabled  01.00.00.4445

[root@host-aep4 ~]# ixpdimm-cli show -pool
Floating point exception (core dumped)
[root@host-aep4 ~]# ixpdimm-cli show -namespace
Floating point exception (core dumped)
[root@host-aep4 ~]# ls /dev/pmem*
/dev/pmem2
[root@host-aep4 ~]# ixpdimm-cli show -log
Time                FileName                                                                                                                      LineNumber LogLevel Message    
02:12:2018:20:18:19 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:17:59 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:17:42 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:17:29 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:20:17:29 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:20:17:27 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:20:17:27 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:20:17:26 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:17:08 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:11:59 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_namespaces.c  1077       Error    'Failed to configure the namespace'
02:12:2018:20:11:59 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_namespaces.c  1043       Error    'Set Sector Size Failed'
02:12:2018:20:11:44 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:11:18 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:11:06 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:20:11:06 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:20:11:04 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:20:11:04 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:20:11:02 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:10:34 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:41 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:20:04:40 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:40 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:37 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:37 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:37 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:37 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:04:37 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:03:38 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:20:03:38 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:20:03:36 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:03:36 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:20:03:36 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:20:03:35 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_adapter_passthrough.c 492        Error    'IOCTL passthrough failed: DSM returned error 655367 for command with Opcode - 0x8 SubOpcode - 0x4 '
02:12:2018:20:03:34 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:20:02:46 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:19:38:02 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:19:34:06 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:19:14:32 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/common/persistence/schema.c   2696       Error    'Running SQL failed, error code 101'
02:12:2018:19:14:32 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/system.c                  298        Error    'Total mapped memory is zero for the socket 1'
02:12:2018:19:14:32 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209        Error    'Failed to retrieve mapped memory information for node_id(1)'
02:12:2018:19:14:32 /quickbuild/workspace/2116/apss_crsw-cr_mgmt/output/rpmbuild/BUILD/ixpdimm_sw-01.00.00.2399/src/lib/lnx_system.c              209  

@djbw @juston-li

**Comment by juston-li** [comment]
This was fixed recently by 9e5fa6c7a58baf72d9d2f21e20e8e6c231cc2d38 in release 01.00.00.2435
