### ISSUE TITLE
what version of invm-frameworks used to build  ixpdimm_sw-01.00.00.2469

### ISSUE THREAD

**Issue by chunglam1999** [01org/ixpdimm_sw#15]
Hi there,

If I build  ixpdimm_sw-01.00.00.2469, what version of invm-frameworks should I used?

**Comment by juston-li** [comment]
Based on the release dates, it looks like the exact build was v01.01.00.2103.

That said, any of the v1.01 should work, no functional changes were made among different build numbers

**Comment by chunglam1999** [comment]
thx for help.
