### ISSUE TITLE
Got "fatal: Not a git repository (or any of the parent directories): .git" when compiling code

### ISSUE THREAD

**Issue by yizhanglinux** [01org/ixpdimm_sw#2]
fatal: Not a git repository (or any of the parent directories): .git
mkdir -p ./output/build/linux/real/debug
mkdir -p ./output/tools/linux/real/debug
make -C src/common  all SKIP_UNITTESTS=1 ADD_MANUFACTURING=0
fatal: Not a git repository (or any of the parent directories): .git
make[1]: Entering directory `/root/ixpdimm_sw-01.00.00.2104/src/common'
make ../../output/obj/linux/real/debug/common/string ../../output/obj/linux/real/debug/common/time ../../output/obj/linux/real/debug/common/guid ../../output/obj/linux/real/debug/common/uid ../../output/obj/linux/real/debug/common/system ../../output/obj/linux/real/debug/common/persistence ../../output/obj/linux/real/debug/common/smbios
fatal: Not a git repository (or any of the parent directories): .git
make[2]: Entering directory`/root/ixpdimm_sw-01.00.00.2104/src/common'
make[2]: `../../output/obj/linux/real/debug/common/string' is up to date.
make[2]:`../../output/obj/linux/real/debug/common/time' is up to date.
make[2]: `../../output/obj/linux/real/debug/common/guid' is up to date.
make[2]:`../../output/obj/linux/real/debug/common/uid' is up to date.
make[2]: `../../output/obj/linux/real/debug/common/system' is up to date.
make[2]:`../../output/obj/linux/real/debug/common/persistence' is up to date.
make[2]: `../../output/obj/linux/real/debug/common/smbios' is up to date.
make[2]: Leaving directory`/root/ixpdimm_sw-01.00.00.2104/src/common'
make -j 65  dependencies
fatal: Not a git repository (or any of the parent directories): .git
make[2]: Entering directory `/root/ixpdimm_sw-01.00.00.2104/src/common'
make persistence/schema.c
fatal: Not a git repository (or any of the parent directories): .git
make[3]: Entering directory`/root/ixpdimm_sw-01.00.00.2104/src/common'
make[3]: Nothing to be done for `persistence/schema.c'.
make[3]: Leaving directory`/root/ixpdimm_sw-01.00.00.2104/src/common'
make file_ops os  
fatal: Not a git repository (or any of the parent directories): .git
make[3]: Entering directory `/root/ixpdimm_sw-01.00.00.2104/src/common'
make -C file_ops all
make -C os all
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
make[4]: Entering directory`/root/ixpdimm_sw-01.00.00.2104/src/common/os'
make -j 65  ../../../output/obj/linux/real/debug/common/os 
make[4]: Entering directory `/root/ixpdimm_sw-01.00.00.2104/src/common/file_ops'
make -j 65  ../../../output/obj/linux/real/debug/common/file_ops 
fatal: Not a git repository (or any of the parent directories): .git
make[5]: Entering directory`/root/ixpdimm_sw-01.00.00.2104/src/common/os'
make[5]: warning: -jN forced in submake: disabling jobserver mode.
fatal: Not a git repository (or any of the parent directories): .git
make[5]: `../../../output/obj/linux/real/debug/common/os' is up to date.
make[5]: Leaving directory`/root/ixpdimm_sw-01.00.00.2104/src/common/os'
make ../../../output/obj/linux/real/debug/common/os/lnx_os.o
make[5]: Entering directory `/root/ixpdimm_sw-01.00.00.2104/src/common/file_ops'
make[5]: warning: -jN forced in submake: disabling jobserver mode.
make[5]:`../../../output/obj/linux/real/debug/common/file_ops' is up to date.
make[5]: Leaving directory `/root/ixpdimm_sw-01.00.00.2104/src/common/file_ops'
make -j 65  ../../../output/obj/linux/real/debug/common/file_ops/file_ops.o ../../../output/obj/linux/real/debug/common/file_ops/lnx_file_ops.o
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
make[5]: Entering directory`/root/ixpdimm_sw-01.00.00.2104/src/common/os'
make[5]: `../../../output/obj/linux/real/debug/common/os/lnx_os.o' is up to date.
make[5]: Leaving directory`/root/ixpdimm_sw-01.00.00.2104/src/common/os'
make[4]: Leaving directory `/root/ixpdimm_sw-01.00.00.2104/src/common/os'
make[5]: Entering directory`/root/ixpdimm_sw-01.00.00.2104/src/common/file_ops'
make[5]: warning: -jN forced in submake: disabling jobserver mode.
make[5]: `../../../output/obj/linux/real/debug/common/file_ops/file_ops.o' is up to date.
make[5]:`../../../output/obj/linux/real/debug/common/file_ops/lnx_file_ops.o' is up to date.
make[5]: Leaving directory `/root/ixpdimm_sw-01.00.00.2104/src/common/file_ops'
make[4]: Leaving directory`/root/ixpdimm_sw-01.00.00.2104/src/common/file_ops'
make[3]: Leaving directory `/root/ixpdimm_sw-01.00.00.2104/src/common'
make encryptdir
fatal: Not a git repository (or any of the parent directories): .git

**Comment by nkothapa** [comment]
This issue has been fixed as of v2112. Please use the latest release v2127 rather than v2104. 

There is a benign git error displayed in the output. I will send out a fix for that shortly. Thanks for the report!
