### ISSUE TITLE
Compatibility with HPE NVDIMM

### ISSUE THREAD

**Issue by Nighthawk75** [01org/ixpdimm_sw#3]
I have an HP DL380 Gen9 and 2 x 8GB HP NVDIMM modules installed.    Fedora has no problem identifying the pmem devices or issuing READ/WRITE commands. 
I am trying to pull attributes like serial numbers, power on hours, health attributes, etc.. by using the ixpdimm-cli software.    

Is this only compatible with Intel XP DIMM modules?

[root@FEDORA rel-release]# lsblk -t
NAME            ALIGNMENT MIN-IO OPT-IO PHY-SEC LOG-SEC ROTA SCHED RQ-SIZE  RA WSAME
pmem0                   0   4096      0    4096     512    0           128 128    0B
pmem1                   0   4096      0    4096     512    0           128 128    0B
sda                     0 262144 262144     512     512    1 cfq       128 128    0B
├─sda2                  0 262144 262144     512     512    1 cfq       128 128    0B
│ ├─fedora-swap         0 262144 262144     512     512    1           128 128    0B
│ ├─fedora-home         0 262144 262144     512     512    1           128 128    0B
│ └─fedora-root         0 262144 262144     512     512    1           128 128    0B
└─sda1                  0 262144 262144     512     512    1 cfq       128 128    0B
[root@FEDORA rel-release]# ndctl list
[
  {
    "dev":"namespace1.0",
    "mode":"raw",
    "size":8589934592,
    "blockdev":"pmem1"
  },
  {
    "dev":"namespace0.0",
    "mode":"raw",
    "size":8589934592,
    "blockdev":"pmem0"
  }
]
[root@FEDORA rel-release]# ixpdimm-cli show -dimm
Error: The command is not supported in the current context.
[root@FEDORA rel-release]# ixpdimm-cli version
Component                         Version
Intel DIMM Gen 1 Software Version 01.00.00.2144
Intel DIMM Gen 1 Driver Version   0.0.0.0

**Comment by ljknippers** [comment]
If you want some basic health information about the HPE NVDIMM, try 'ndctl list --dimms --idle --health'.  We are in the process of adding more health information to that utility.    For now, you'll see information like:
  {
    "dev":"nmem6",
    "id":"802c-0f-1612-122eb278",
    "health":{
      "health_state":"ok",
      "temperature_celsius":25.000000,
      "spares_percentage":99,
      "alarm_temperature":false,
      "alarm_spares":false,
      "temperature_threshold":50.000000,
      "spares_threshold":20,
      "life_used_percentage":0,
      "shutdown_state":"clean"
    }
  },

Note that to get the health information, you'll need to have the acpi_ipmi kernel module loaded.

**Comment by Nighthawk75** [comment]
That worked great.   Thank you.
I was hoping to see the sensor attributes like what is defined in the ixpdimm-cli:
MediaTemperature
ControllerTemperature
SpareCapacity - desired
WearLevel - desired 
UnsafeShutdowns - desired
PowerOnTime - desired
UpTime|PowerCycles - desired
FWErrorCount - desired
PowerLimited
MediaErrorsUncorrectable - desired 
MediaErrorsCorrected - desired
MediaErrorsErasureCoded - desired
WriteCountMax
WriteCountAvg
MediaErrorsHost
MediaErrorsNonHost
