### ISSUE TITLE
An error with VIKING NVDIMM

### ISSUE THREAD

**Issue by norjar** [01org/ixpdimm_sw#4]
My machine is made by SUPERMICRO with 2 x 8G VIKING NVDIMMs and one 8G DRAM. 
My operating system on the machine is suse linux enterprise server 12 sp2 (SLES12 SP2).
I have followed your steps to install this ixpdimm-cli and ixpdimm-monitor tools except for your prebuilt fedora 4.3 kernel and my os kernel version is 4.4.21.
Everything seems to be ok until I use the command line `ixpdimm-cli show -dimm` or `ixpdimm-cli version.`
As you can see below, It reminders me that some softwares are built incorrectly.
```
linux-4o54:/home/viking/Downloads/ixpdimm_sw # ixpdimm-cli version
Component                         Version                                                                                                 
Intel DIMM Gen 1 Software Version 01.00.00.2264                                                                                          
Intel DIMM Gen 1 Driver Version   Error: The underlying software is missing or incompatible with this version of the management software. 
linux-4o54:/home/viking/Downloads/ixpdimm_sw # ixpdimm-cli show -dimm
Error: The underlying software is missing or incompatible with this version of the management software.
```
And the results below are shown by the tool ndctl.
```
linux-4o54:/home/viking/Downloads/ixpdimm_sw # ndctl list
[
  {
    "dev":"namespace0.0",
    "mode":"memory",
    "size":17179869184,
    "blockdev":"pmem0"
  }
]
```
Then, what can I do?
Could you give me some suggestions?

**Comment by rgkarkha** [comment]
Hello, can you do an lsmod and make sure if the nfit module is loaded in the kernel ?
Thanks,
Rutvij

**Comment by djbw** [comment]
@rgkarkha "ndctl list" is showing the namespace so the nfit and modules are fine. This is probably related to the fact that ixpdimm_sw expects some sysfs attributes that do not appear until the v4.7 kernel.

**Comment by rgkarkha** [comment]
@norjar As suggested above, please install the the latest kernel to resolve your issue.

**Comment by norjar** [comment]
@rgkarkha @djbw I have installed the v4.12 kernel and further reinstalled ixpdimm, but it doesn't work.  :(

**Comment by djbw** [comment]
@norjar sorry to hear that. Does ndctl give you what you need? For the foreseeable future the ndctl utility is the tool for cross-vendor nvdimm support in Linux.

**Comment by norjar** [comment]
@djbw The ndctl utility can help me to manage NVDIMM, but I have something wrong with this tool. Therefore, I just want to try another tools to manage it. Thanks for your help. :)
