### ISSUE TITLE
there are more than 2 linux distributions in the world, including Intel's own linux distribution (Clear Linux)

### ISSUE THREAD

**Issue by fenrus75** [01org/ixpdimm_sw#6]
ifneq ("$(wildcard /etc/redhat-release)","")
                        LINUX_DIST := rel
                else ifneq ("$(wildcard /etc/SuSE-release)","")
                        LINUX_DIST := sle
                else
                        LINUX_DIST := $(warning Unrecognized Linux distribution)
                endif

**Comment by juston-li** [comment]
Recent CMake changes should support compiling and installing regardless of user distribution.

Some defines still remain for generating RPM's for specific distros.
