### ISSUE TITLE
Errror when compile ixpdimm_sw-01.00.00.2345 (same error on ixpdimm_sw-01.00.00.2366)

### ISSUE THREAD

**Issue by chunglam1999** [01org/ixpdimm_sw#9]
/usr/bin/cc  -DCMPI_PLATFORM_LINUX_GENERIC_GNU=1 -DRELEASE -D_GNU_SOURCE -D__ADD_MANUFACTURING__=1 -D__LARGE_PAYLOAD__=1 -D__LINUX__ -D__NVM_DLL__ -D__PRODUCT_DATADIR__=\"/var/lib/ixpdimm_sw/\" -D__VERSION_BUILDNUM__=2345 -D__VERSION_HOTFIX__=00 -D__VERSION_MAJOR__=01 -D__VERSION_MINOR__=00 -D__VERSION_NUMBER__=01.00.00.2345 -D__WBEM_PREFIX__=Intel_ -Dixpdimm_EXPORTS -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -std=c99 -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -ggdb -fstack-protector-all -D_XOPEN_SOURCE=500 -Wall -Werror -Wfatal-errors -MMD -z noexecstack -z relro -z now -pie -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fPIC -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/ixpdimm -isystem /builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/PUBLIC -isystem /builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/external/os_headers -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/acpi -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/external/fw_headers -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/common -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/lib    -O2 -fno-strict-aliasing -fPIC -o CMakeFiles/ixpdimm.dir/src/lib/lnx_system.c.o   -c /builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/lib/lnx_system.c
/usr/bin/cmake -E cmake_progress_report /builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/CMakeFiles 45
[ 45%] Building C object CMakeFiles/ixpdimm.dir/src/lib/lnx_adapter_namespaces.c.o
/usr/bin/cc  -DCMPI_PLATFORM_LINUX_GENERIC_GNU=1 -DRELEASE -D_GNU_SOURCE -D__ADD_MANUFACTURING__=1 -D__LARGE_PAYLOAD__=1 -D__LINUX__ -D__NVM_DLL__ -D__PRODUCT_DATADIR__=\"/var/lib/ixpdimm_sw/\" -D__VERSION_BUILDNUM__=2345 -D__VERSION_HOTFIX__=00 -D__VERSION_MAJOR__=01 -D__VERSION_MINOR__=00 -D__VERSION_NUMBER__=01.00.00.2345 -D__WBEM_PREFIX__=Intel_ -Dixpdimm_EXPORTS -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -std=c99 -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -ggdb -fstack-protector-all -D_XOPEN_SOURCE=500 -Wall -Werror -Wfatal-errors -MMD -z noexecstack -z relro -z now -pie -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fPIC -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/ixpdimm -isystem /builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/PUBLIC -isystem /builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/external/os_headers -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/acpi -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/external/fw_headers -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/common -I/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/lib    -O2 -fno-strict-aliasing -fPIC -o CMakeFiles/ixpdimm.dir/src/lib/lnx_adapter_namespaces.c.o   -c /builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/lib/lnx_adapter_namespaces.c
/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/src/lib/lnx_adapter_namespaces.c:549:32: error: 'enum ndctl_namespace_version' declared inside parameter list [-Werror]
  struct ndctl_dimm *dimm, enum ndctl_namespace_version v)
                                ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/ixpdimm.dir/src/lib/lnx_adapter_namespaces.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345'
make[1]: *** [CMakeFiles/ixpdimm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Created apss.dat
make[2]: Leaving directory `/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345'
/usr/bin/cmake -E cmake_progress_report /builddir/build/BUILD/ixpdimm_sw-01.00.00.2345/CMakeFiles 
[ 45%] Built target db_creator
make[1]: Leaving directory `/builddir/build/BUILD/ixpdimm_sw-01.00.00.2345'

**Comment by juston-li** [comment]
Update ndctl to 58.2+

**Comment by chunglam1999** [comment]
Thanks for help.

**Comment by insanecoderr** [comment]
is that when compling master branch, the ndctl should be 58.2+ too? @juston-li
